// lib/addons/Backup/WebClient_Old/src/components/content/MainHeader.vue
<script setup lang="ts">

import TopbarTittle from "@/components/content/TopbarTittle.vue";
import ThemeToogle from "@/components/content/ThemeToogle.vue";
import Sidebar from "@/components/content/Sidebar.vue";

import {settingsData} from "@/state/state.ts";

</script>

<template>
  <header class="sticky z-50 top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
    <Topbar></Topbar>
    <Sidebar></Sidebar>

    <div class="flex w-full items-center text-center gap-4 md:ml-auto md:gap-2 lg:gap-4">
      <TopbarTittle></TopbarTittle>
      <div v-if="settingsData.themes.value == 'modern'">
        <ThemeToogle></ThemeToogle>
      </div>

    </div>
  </header>
</template>

<style scoped>

</style>

// lib/addons/AutoLightv3/WebClient/components/content/MainHeader.tsx
"use client"

import TopbarTitle from "@/components/content/TopbarTitle"
import ThemeToggle from "@/components/content/ThemeToggle"
import Sidebar from "@/components/content/Sidebar"
import ConnectionStatus from "@/components/content/ConnectionStatus"
import { useALS } from "@/lib/contexts/ALSContext"

export default function MainHeader() {
  const { settingsData } = useALS()

  return (
    <header className="sticky z-50 top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
      <Sidebar />
      
      <div className="flex w-full items-center text-center gap-4 md:ml-auto md:gap-2 lg:gap-4">
        <TopbarTitle />
        <div className="flex items-center gap-2 ml-auto">
          <ConnectionStatus />
          {settingsData.themes === 'modern' && (
            <ThemeToggle />
          )}
        </div>
      </div>
    </header>
  )
}
